# Generated by Django 4.1 on 2022-11-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClothing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prenda', models.CharField(max_length=50)),
                ('talle', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('tipo_prenda', models.CharField(max_length=50)),
            ],
        ),
    ]
