# Generated by Django 4.1 on 2022-11-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamily', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
    ]
